import type { EventObservation, ResearchRun } from '../api/schemas.ts'

export const TEST_RUN: ResearchRun = {
  run_id: '20260101T000000Z',
  schema_version: 1,
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-01-01T00:00:00Z',
  disclosure_start_date: '2025-01-01',
  disclosure_end_date: '2025-12-31',
  target_events: 40,
  stages: { opendart_sample: 'complete', outcomes: 'blocked' },
  counts: { selected_events: 1, attention_observed: 1, abnormal_h1_observed: 0 },
  interpretation: 'Test-only fixture.',
  blockers: ['outcomes is blocked.'],
  readable: true,
}

export const TEST_EVENT: EventObservation = {
  receipt_number: '20260101000001',
  ticker: '000001',
  corporation_name: 'Test Corporation',
  report_name: 'Single-Sales and Supply Contract',
  market_class: 'Y',
  received_date: '2026-01-01',
  contract_amount_krw: '1000000000',
  recent_revenue_krw: '10000000000',
  reported_revenue_ratio_percent: '10.0',
  computed_revenue_ratio_percent: '10.0',
  ratio_difference_percentage_points: '0.0',
  contract_revenue_ratio: 0.1,
  baseline_observed_days: 20,
  event_observed_days: 3,
  baseline_median_ratio: 1,
  event_mean_ratio: 2,
  attention_excess: 2,
  attention_group: 'higher_attention',
  attention_missing_reason: '',
  decision_date: null,
  raw_return_h0: null,
  raw_return_h1: null,
  raw_return_h3: null,
  raw_return_h5: null,
  market_return_h0: null,
  market_return_h1: null,
  market_return_h3: null,
  market_return_h5: null,
  abnormal_return_h0: null,
  abnormal_return_h1: null,
  abnormal_return_h3: null,
  abnormal_return_h5: null,
  price_missing_reason: 'test_price_missing',
  index_missing_reason: 'test_index_missing',
  outcome_state: 'missing',
  source_document_sha256: 'a'.repeat(64),
  attention_source_snapshot_sha256: 'b'.repeat(64),
}
